spring:
  application:
    name: stats-server
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    com.netflix: WARN
    org.springframework.cloud: INFO
    ru.practicum: DEBUG