server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: stats-server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/stat-db
    username: stat-db
    password: stat-db
  sql:
    init:
      mode: always

hibernate:
  show_sql: false
  jdbc:
    time_zone: UTC