spring:
  application:
    name: main-service
  config:
    import: "optional:configserver:"
  cloud:
     config:
       discovery:
         enabled: true
         service-id: config-server
       fail-fast: true
       retry:
         use-random-policy: true
         max-interval: 6000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # какие эндпоинты открывать
      base-path: /actuator  # путь к эндпоинтам (по умолчанию)
  endpoint:
    health:
      show-details: always  # показывать детали здоровья
      show-components: always
      probes:
        enabled: true  # включить liveness и readiness probes
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: true  # проверка БД
    diskspace:
      enabled: true  # проверка дискового пространства

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health  # для Eureka health checks
    status-page-url-path: /actuator/info

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.commons: DEBUG
    com.netflix: WARN
    org.springframework.cloud: INFO